package epaecho

// EchoFacility holds all data associated with a facility returned
// from an EchoFacilities API request.
//
// The ECHO API by default returns string values for all fields
// within the JSON response. Therefore the echoBool, echoFloat, echoInt and
// echoDate custom types are provided to properly unmarshal the string data to
// an appropriate data structure.
type EchoFacility struct {
	RegistryID                        string    `json:"RegistryID"`
	Name                              string    `json:"FacName"`
	Street                            string    `json:"FacStreet,omitempty"`
	City                              string    `json:"FacCity,omitempty"`
	State                             string    `json:"FacState,omitempty"`
	Zip                               string    `json:"FacZip,omitempty"`
	County                            string    `json:"FacCounty,omitempty"`
	FIPSCode                          string    `json:"FacFIPSCode,omitempty"`
	EPARegion                         string    `json:"FacEPARegion,omitempty"`
	IndianCountry                     echoBool  `json:"FacIndianCntryFlg,omitemtpy"`
	FederalFacility                   echoBool  `json:"FacFederalFlg,omitemtpy"`
	USMexBorder                       echoBool  `json:"FacUsMexBorderFlg,omitempty"`
	ChesapeakeBay                     echoBool  `json:"FacChesapeakeBayFlag,omitempty"`
	NAAArea                           echoBool  `json:"FacNaaFlag,omitempty"`
	Latitude                          echoFloat `json:"FacLat,omitempty"`
	Long                              echoFloat `json:"FacLong,omitempty"`
	MapIcon                           string    `json:"FacMapIcon,omitempty"`
	LatLongCollectionMethod           string    `json:"FacCollectionMethod,omitempty"`
	LatLongDescription                string    `json:"FacReferencePoint,omitempty"`
	LatLongAccuracy                   echoFloat `json:"FacAccuracyMeters,omitempty"`
	LocalTribes                       string    `json:"FacDerivedTRIbes,omitempty"`
	WatershedHUC                      string    `json:"FacDerivedHuc,omitempty"`
	WatershedBoundaryDatasetCode      string    `json:"FacDerivedWbd,omitempty"`
	StateCountyFIPSCode               string    `json:"FacDerivedStctyFIPS,omitempty"`
	LatLongZip                        string    `json:"FacDerivedZip,omitempty"`
	CongressionalDistrict             string    `json:"FacDerivedCd113,omitempty"`
	CensusBlock                       string    `json:"FacDerivedCb2010,omitempty"`
	PercentMinority                   string    `json:"FacPercentMinority,omitempty"`
	PopulationDensity                 echoFloat `json:"FacPopDen,omitempty"`
	Major                             echoBool  `json:"FacMajorFlag,omitempty"`
	Active                            echoBool  `json:"FacActiveFlag,omitempty"`
	MYRTKUniverse                     string    `json:"FacMyrtkUniverse,omitempty"`
	InspectionCount                   echoInt   `json:"FacInspectionCount,omitempty"`
	LastInspectionDate                echoDate  `json:"FacDateLastInspection,omitempty"`
	DaysSinceLastInspection           echoInt   `json:"FacDaysLastInspection,omitempty"`
	InformalActionCount               echoInt   `json:"FacInformalCount,omitempty"`
	LastInformalActionDate            echoDate  `json:"FacDateLastInformalAction,omitempty"`
	FormalActionCount                 echoInt   `json:"FacFormalActionCount,omitempty"`
	LastFormalActionDate              echoDate  `json:"FacDateLastFormalAction,omitempty"`
	TotalPenalties                    string    `json:"FacTotalPenalties,omitempty"`
	PenaltyCount                      echoInt   `json:"FacPenaltyCount,omitempty"`
	LastPenaltyDate                   echoDate  `json:"FacDateLastPenalty,omitempty"`
	LastPenaltyAmount                 string    `json:"FacLastPenaltyAmt,omitempty"`
	QuartersInNonCompliance           string    `json:"FacQtrsInNC,omitempty"`
	ProgramsInSeriousNonCompliance    echoInt   `json:"FacProgramsInSNC,omitempty"`
	CurrentComplianceStatus           string    `json:"FacCurrComplianceStatus,omitempty"`
	CurrentSeriousNonCompliance       echoBool  `json:"FacCurrSNCFlg,omitempty"`
	ComplianceStatusThreeYear         string    `json:"Fac3yrComplianceStatus,omitempty"`
	HasAirID                          echoBool  `json:"AIRFlag,omitempty"`
	HasCWAID                          echoBool  `json:"NPDESFlag,omitempty"`
	HasSDWISID                        echoBool  `json:"SdwisFlag,omitempty"`
	HasRCRAID                         echoBool  `json:"RCRAFlag,omitempty"`
	HasTRIID                          echoBool  `json:"TRIFlag,omitempty"`
	HasGHGID                          echoBool  `json:"GHGFlag,omitempty"`
	AirIDs                            string    `json:"AIRIDs,omitempty"`
	CAAPermitTypes                    string    `json:",omitempty"`
	CAANAICSID                        string    `json:"CAANaics,omitempty"`
	CAASICCodes                       string    `json:"CAASics,omitempty"`
	CAAEvaluationCount                echoInt   `json:",omitempty"`
	CAADaysSinceLastEvaluation        echoInt   `json:"CAADaysLastEvaluation,omitempty"`
	CAAInformalCount                  echoInt   `json:"CAAInformalCount,omitempty"`
	CAAFormalActionCount              echoInt   `json:"CAAFormalActionCount,omitempty"`
	CAALastFormalActionDate           echoDate  `json:"CAADateLastFormalAction,omitempty"`
	CAAPenalties                      string    `json:"CAAPenalties,omitempty"`
	CAALastPenaltyDate                echoDate  `json:"CAALastPenaltyDate,omitempty"`
	CAALastPenaltyAmount              string    `json:"CAALastPenaltyAmt,omitempty"`
	CAAQuarternsInNonCompliance       echoInt   `json:"CAAQtrsInNC,omitempty"`
	CAACurrentComplianceStatus        string    `json:"CAACurrComplianceStatus,omitempty"`
	CAACurrentHPV                     echoBool  `json:"CAACurrHpvFlag,omitempty"`
	CAACompliance3Year                string    `json:"CAA3yrComplQtrsStatus,omitempty"`
	NPDESIDs                          string    `json:",omitempty"`
	CWAPermitTypes                    string    `json:",omitempty"`
	CWAComplianceTracking             string    `json:",omitempty"`
	CWANAICSCode                      string    `json:"CWANaics,omitempty"`
	CWASICCodes                       string    `json:"CWASics,omitempty"`
	CWAInspectionCount                echoInt   `json:",omitempty"`
	CWADaysLastInspection             string    `json:",omitempty"`
	CWAInformalCount                  echoInt   `json:",omitempty"`
	CWAFormalActionCount              echoInt   `json:",omitempty"`
	CWALastFormalActionDate           echoDate  `json:"CWADateLastFormalAction,omitempty"`
	CWAPenalties                      string    `json:",omitempty"`
	CWALastPenaltyDate                echoDate  `json:",omitempty"`
	CWALastPenaltyAmount              string    `json:"CWALastPenaltyAmt,omitempty"`
	CWAQuartersInNonCompliance        echoInt   `json:"CWAQtrsInNC,omitempty"`
	CWACurrentComplianceStatus        string    `json:"CWACurrComplianceStatus,omitempty"`
	CWASignificantNonCompliance       echoBool  `json:"CWACurrSNCFlag"`
	CWAThreeYearNonComplianceStatus   string    `json:"CWA13qtrsComplStatus"`
	CWAThreeYearEECount               echoInt   `json:"CWA13qtrsEfflntExceedances,omitempty"`
	CWAThreeYearNonComplianceCodes    string    `json:"CWA3YrQncrCodes,omitempty"`
	RCRAIDs                           string    `json:",omitempty"`
	RCRAPermitTypes                   string    `json:",omitempty"`
	RCRANAICSCode                     string    `json:"RCRANaics,omitempty"`
	RCRAInspectionCount               echoInt   `json:",omitempty"`
	RCRALastEvaluationDate            echoDate  `json:"RCRADaysLastEvaluation,omitempty"`
	RCRAInformalActionCount           echoInt   `json:"RCRAInformalCount,omitempty"`
	RCRAFormalActionCount             echoInt   `json:",omitempty"`
	RCRALastFormalActionDate          echoDate  `json:"RCRADateLastFormalAction,omitempty"`
	RCRAPenalties                     string    `json:",omitempty"`
	RCRALastPenaltyDate               echoDate  `json:",omitempty"`
	RCRALastPenaltyAmount             string    `json:"RCRALastPenaltyAmt,omitempty"`
	RCRAQuartersInNonCompliance       echoInt   `json:"RCRAQtrsInNC,omitempty"`
	RCRACurrentComplianceStatus       string    `json:"RCRACurrComplianceStatus,omitempty"`
	RCRASignificantNonCompliance      echoBool  `json:"RCRACurrSNCFlag,omitempty"`
	RCRAThreeYearComplianceStatus     string    `json:"RCRA3yrComplQtrsStatus,omitempty"`
	SDWAIDs                           string    `json:",omitempty"`
	SDWASystemTypes                   string    `json:",omitempty"`
	SDWAInformalActionCount           echoInt   `json:"SDWAInformalCount,omitempty"`
	SDWAFormalActionCount             echoInt   `json:",omitempty"`
	SDWACurrentComplianceStatus       string    `json:"SDWACurrComplianceStatus,omitempty"`
	SDWSignificationNoncompliance     echoBool  `json:"SDWACurrSNCFlag,omitempty"`
	TRIIDs                            string    `json:",omitempty"`
	TRITotalReleasedPerYearTransfers  echoInt   `json:"TRIReleasesTransfers,omitempty"`
	TRITotalReleasedPerYearOnsite     echoInt   `json:"TRIOnSiteReleases,omitempty"`
	TRITotalTransferredPerYearOffsite echoInt   `json:"TRIOffSiteTransfers,omitempty"`
	TRIPreviousReport                 echoBool  `json:"TRIReporterInPast,omitempty"`
	FECCaseIDs                        string    `json:"FecCaseIDs,omitempty"`
	FECNumberOfCases                  echoInt   `json:"FecNumberOfCases,omitempty"`
	FECLastCaseDate                   echoDate  `json:"FecLastCaseDate,omitempty"`
	FECTotalPenalties                 echoInt   `json:"FecTotalPenalties,omitempty"`
	GHGIDs                            string    `json:",omitempty"`
	GHGReleases                       echoInt   `json:"GHGCO2Releases,omitempty"`
	ReportURL                         string    `json:"DfrUrl,omitempty"`
	SICCodes                          string    `json:"FacSicCodes,omitempty"`
	NAICSCodes                        string    `json:"FacNaicsCodes,omitempty"`
	LastEPAInspectionDate             echoDate  `json:"FacDateLastInspectionEPA,omitempty"`
	LastStateInspectionDate           echoDate  `json:"FacDateLastInspectionState,omitempty"`
	LastFormalEPAActionDate           echoDate  `json:"FacDateLastFormalActEPA,omitempty"`
	LastFormalStateActionDate         echoDate  `json:"FacDateLastFormalActSt,omitempty"`
	LastInformalEPAActionDate         echoDate  `json:"FacDateLastInformalActEPA,omitempty"`
	LastInformalStateActionDate       echoDate  `json:"FacDateLastInformalActSt,omitempty"`
	FederalAgencyCode                 string    `json:"FacFederalAgency,omitempty"`
	ReportedTRI                       echoBool  `json:"TRIReporter,omitempty"`
	CleanWaterDischarge               echoBool  `json:"FacImpWaterFlg,omitempty"`
	SourceID                          string    `json:"SourceID,omitempty"`
	NonCompliance                     echoBool  `json:"NC,omitempty"`
	RMPIds                            string    `json:"RmpIDs,omitempty"`
}
